In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#read
df=pd.read_csv('/content/zepto_data.csv')
df.head()

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
0,1000018,Zepto,Delhi,23,1041.42975,5.000,14.74,18.0,Snacks,Wallet,NaN,1.0,NaN
1,1000028,Zepto,Hyderabad,43,50.00000,12.140,11.90,19.0,Snacks,Credit Card,3.5,1.0,3.5
2,1000030,Zepto,Mumbai,57,539.09325,7.582,5.97,4.0,Beverages,Debit Card,3.4,1.0,4.7
3,1000044,Zepto,NaN,51,543.44850,5.000,2.32,8.0,Snacks,UPI,2.5,0.0,3.1
4,1000048,Zepto,Bengluru,40,1300.33200,13.388,13.98,6.0,Personal Care,UPI,2.4,1.0,3.3

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41024 entries, 0 to 43325
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Order_ID                 41024 non-null  int64
 1   Company                  41024 non-null  object
 2   City                     41024 non-null  object
 3   Customer_Age             41024 non-null  int64
 4   Order_Value              41024 non-null  float64
 5   Delivery_Time_Min        41024 non-null  float64
 6   Distance_Km              41024 non-null  float64
 7   Items_Count              39652 non-null  float64
 8   Product_Category         41024 non-null  object
 9   Payment_Method           41024 non-null  object
 10  Customer_Rating          39187 non-null  float64
 11  Discount_Applied         41024 non-null  float64
 12  Delivery_Partner_Rating  36812 non-null  float64
dtypes: float64(7), int64(2), object(4)
memory usage: 4.4+ MB

In [ ]:
#describe stats
df.describe()

,Order_ID,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
count,4.332600e+04,43326.000000,43326.000000,43326.00000,43326.00000,41878.000000,41368.000000,43326.000000,38891.000000
mean,1.173527e+06,38.418248,593.472095,9.54603,7.73949,10.003056,3.205333,0.399852,3.747646
std,1.000078e+05,12.127473,395.177253,4.29168,4.17865,5.464956,1.159980,0.489873,0.720339
min,1.000018e+06,18.000000,50.000000,5.00000,0.50000,1.000000,1.000000,0.000000,2.500000
25%,1.087332e+06,28.000000,304.093875,6.01050,4.14000,5.000000,2.200000,0.000000,3.100000
50%,1.173951e+06,38.000000,556.900000,8.84200,7.73000,10.000000,3.200000,0.000000,3.700000
75%,1.260205e+06,49.000000,826.790625,11.53200,11.35000,15.000000,4.200000,1.000000,4.400000
max,1.345973e+06,59.000000,11196.438750,25.98800,15.00000,19.000000,5.000000,1.000000,5.000000

In [ ]:
df.isna().sum()

Order_ID                      0
Company                       0
City                       2302
Customer_Age                  0
Order_Value                   0
Delivery_Time_Min             0
Distance_Km                   0
Items_Count                1448
Product_Category              0
Payment_Method                0
Customer_Rating            1958
Discount_Applied              0
Delivery_Partner_Rating    4435
dtype: int64

In [ ]:
#To show the records which contains any or all null values
df[df.isna().any(axis=1)]

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
0,1000018,Zepto,Delhi,23,1041.42975,5.000,14.74,18.0,Snacks,Wallet,NaN,1.0,NaN
3,1000044,Zepto,NaN,51,543.44850,5.000,2.32,8.0,Snacks,UPI,2.5,0.0,3.1
14,1000138,Zepto,Hyderabad,25,290.66625,12.352,13.92,14.0,Fruits & Vegetables,Cash on Delivery,1.6,1.0,NaN
15,1000140,Zepto,Chennai,37,443.59350,13.004,13.34,19.0,Dairy,Cash on Delivery,2.2,0.0,NaN
20,1000209,Zepto,NaN,35,714.59850,10.088,8.48,19.0,Household,Debit Card,5.0,0.0,4.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43305,1345872,Zepto,Hyderabad,49,368.35050,5.000,0.64,1.0,Snacks,Debit Card,NaN,0.0,3.7
43316,1345953,Zepto,Hyderabad,42,593.53350,6.762,6.27,17.0,Dairy,Debit Card,3.7,0.0,NaN
43317,1345956,Zepto,NaN,41,415.91550,12.616,14.36,12.0,Dairy,Wallet,2.1,0.0,3.3
43321,1345962,Zepto,Delhi,54,119.51650,5.000,5.32,14.0,Fruits & Vegetables,Cash on Delivery,1.8,0.0,NaN
43325,1345973,Zepto,Amritsar,21,859.75050,10.492,10.82,NaN,Snacks,Wallet,3.0,0.0,3.1

In [ ]:
df[df.isna().all(axis=1)]

Empty DataFrame
Columns: [Order_ID, Company, City, Customer_Age, Order_Value, Delivery_Time_Min, Distance_Km, Items_Count, Product_Category, Payment_Method, Customer_Rating, Discount_Applied, Delivery_Partner_Rating]
Index: []

In [ ]:
#removing all the records where city is NaN since its a string
df=df.dropna(subset=['City'])

In [ ]:
df.isna().sum()

Order_ID                      0
Company                       0
City                          0
Customer_Age                  0
Order_Value                   0
Delivery_Time_Min             0
Distance_Km                   0
Items_Count                1372
Product_Category              0
Payment_Method                0
Customer_Rating            1837
Discount_Applied              0
Delivery_Partner_Rating    4212
dtype: int64

In [ ]:
df["Items_Count"].skew()

np.float64(-0.002192493477327754)

In [ ]:
#Items_Count showed near-zero skewness (-0.002), indicating symmetric distribution.
#Missing values were imputed using median to maintain robustness.
df["Items_Count"]=df["Items_Count"].fillna(df["Items_Count"].median())

In [ ]:
df.isna().sum()

Order_ID                      0
Company                       0
City                          0
Customer_Age                  0
Order_Value                   0
Delivery_Time_Min             0
Distance_Km                   0
Items_Count                   0
Product_Category              0
Payment_Method                0
Customer_Rating            1837
Discount_Applied              0
Delivery_Partner_Rating    4212
dtype: int64

In [ ]:
df["Customer_Rating"].skew()

np.float64(-0.04806541010620432)

In [ ]:
#Customer_Rating shows near-zero skewness (-0.048), indicating a fairly symmetric distribution.
#Missing values were imputed using the median,
#as it is more appropriate for ordinal rating data and robust to extremes.
df["Customer_Rating"]=df["Customer_Rating"].fillna(df["Customer_Rating"].median())

In [ ]:
df["Delivery_Partner_Rating"].skew()

np.float64(0.010805011727727598)

In [ ]:
#Delivery_Partner_Rating shows no significant skewness.
#Missing values can be safely imputed using the median,
#as it is suitable for ordinal rating data.
df["Delivery_Partner_Rating"]=df["Delivery_Partner_Rating"].fillna(df["Delivery_Partner_Rating"].median())

In [ ]:
df.head()

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating,Customer_Ratingt
0,1000018,Zepto,Delhi,23,1041.42975,5.000,14.74,18.0,Snacks,Wallet,3.2,1.0,3.7,3.2
1,1000028,Zepto,Hyderabad,43,50.00000,12.140,11.90,19.0,Snacks,Credit Card,3.5,1.0,3.5,3.5
2,1000030,Zepto,Mumbai,57,539.09325,7.582,5.97,4.0,Beverages,Debit Card,3.4,1.0,4.7,3.4
4,1000048,Zepto,Bengluru,40,1300.33200,13.388,13.98,6.0,Personal Care,UPI,2.4,1.0,3.3,2.4
5,1000064,Zepto,Pune,38,229.17300,5.000,0.70,5.0,Beverages,Cash on Delivery,4.0,0.0,4.4,4.0

In [ ]:
df.isna().sum()

Order_ID                   0
Company                    0
City                       0
Customer_Age               0
Order_Value                0
Delivery_Time_Min          0
Distance_Km                0
Items_Count                0
Product_Category           0
Payment_Method             0
Customer_Rating            0
Discount_Applied           0
Delivery_Partner_Rating    0
Customer_Ratingt           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

,Order_ID,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Customer_Rating,Discount_Applied,Delivery_Partner_Rating,Customer_Ratingt
count,4.102400e+04,41024.000000,41024.000000,41024.000000,41024.000000,41024.000000,41024.000000,41024.000000,41024.000000,41024.000000
mean,1.173543e+06,38.421802,593.801326,9.620594,7.741656,9.998269,3.204444,0.400668,3.742351,3.204444
std,1.000390e+05,12.125757,396.182110,4.359683,4.179456,5.376235,1.135307,0.490040,0.682249,1.135307
min,1.000018e+06,18.000000,50.000000,5.000000,0.500000,1.000000,1.000000,0.000000,2.500000,1.000000
25%,1.087264e+06,28.000000,304.228500,6.020000,4.140000,5.000000,2.300000,0.000000,3.200000,2.300000
50%,1.173951e+06,38.000000,557.292875,8.890000,7.730000,10.000000,3.200000,0.000000,3.700000,3.200000
75%,1.260292e+06,49.000000,826.860938,11.638000,11.352500,15.000000,4.200000,1.000000,4.300000,4.200000
max,1.345973e+06,59.000000,11196.438750,25.988000,15.000000,19.000000,5.000000,1.000000,5.000000,5.000000

In [ ]:
df = df.drop(columns=["Customer_Ratingt"])

In [ ]:
# EDA ANALYSIS
# basic business KPIs

In [ ]:
# Total revenue
df['Order_Value'].sum()

np.float64(24360105.59325)

In [ ]:
# Average order value
df["Order_Value"].mean()

np.float64(593.8013258885043)

In [ ]:
# Total Orders
df["Order_ID"].nunique()

41024

In [ ]:
# City-wise Performance
# Revenue by City
df.groupby("City")["Order_Value"].sum().sort_values(ascending=False)

City
Noida        2.438189e+06
Gurgaon      2.389289e+06
Delhi        2.206950e+06
Mumbai       2.096956e+06
Bengluru     2.054087e+06
Chennai      2.051725e+06
Pune         2.022608e+06
Hyderabad    2.006389e+06
Kolkata      1.991253e+06
Amritsar     1.977788e+06
Jaipur       1.592011e+06
Haridwar     1.532860e+06
Name: Order_Value, dtype: float64

In [ ]:
# Avg Delivery Time by City
df.groupby("City")["Delivery_Time_Min"].mean().sort_values()

City
Delhi         5.000000
Chennai       8.279395
Noida         8.286586
Gurgaon       8.300052
Kolkata       8.329249
Amritsar      8.339013
Hyderabad     8.355702
Pune          8.386603
Bengluru      9.171465
Mumbai       10.112339
Jaipur       13.129537
Haridwar     20.124645
Name: Delivery_Time_Min, dtype: float64

In [ ]:
#Avg Customer Rating by City
df.groupby("City")["Customer_Rating"].mean().sort_values(ascending=False)

City
Bengluru     3.630299
Mumbai       3.398630
Delhi        3.275819
Gurgaon      3.231565
Noida        3.217903
Pune         3.206391
Haridwar     3.190071
Kolkata      3.186039
Amritsar     3.177817
Chennai      3.157872
Jaipur       3.126139
Hyderabad    2.669442
Name: Customer_Rating, dtype: float64

In [ ]:
# Discount Impact
# This code calculates the average order value for orders with and without discounts.
# It helps determine whether applying discounts increases overall customer spending.
df.groupby("Discount_Applied")["Order_Value"].mean()

NameError: name 'df' is not defined

In [ ]:
# This code computes the average number of items purchased for discounted and non-discounted orders.
# It helps assess whether discounts encourage customers to buy more items per order.
df.groupby("Discount_Applied")["Items_Count"].mean()

Discount_Applied
0.0    10.025054
1.0     9.958204
Name: Items_Count, dtype: float64

In [ ]:
# Correlation Check
# This code checks how delivery time and distance are related to customer ratings.
# It helps see if slower or longer deliveries lead to lower ratings.
df[["Delivery_Time_Min","Customer_Rating","Distance_Km"]].corr()

                   Delivery_Time_Min  Customer_Rating  Distance_Km
Delivery_Time_Min           1.000000        -0.000994     0.492250
Customer_Rating            -0.000994         1.000000     0.000528
Distance_Km                 0.492250         0.000528     1.000000